version: '2'

services:
  profiler:
    image: spark-profiler:latest
    container_name: spark-profiler
    environment:
      SPARK_MASTER: "spark://spark-master:7077"
      INFLUX_HOST: "influxdb"
      INFLUX_HTTP_PORT: "8086"
      INFLUX_DATABASE_NAME: "spark"
      INFLUX_USERNAME: "admin"
      INFLUX_PASSWORD: "admin"
      FLAMEGRAPH_TITLE: "Spark Application"
    volumes:
      - ./graphs:/graphs
    env_file:
      - ./hadoop-hive.env

networks:
  default:
    external:
      name: spark-profiling
